# Generated by Django 3.0.6 on 2020-05-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workspaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('address', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='sample')),
                ('capacity', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
