# Generated by Django 3.0.6 on 2020-05-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaces',
            name='price',
            field=models.CharField(default='Not Available', max_length=50),
        ),
    ]
