# Generated by Django 3.0.6 on 2020-06-01 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_workspaces_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('booked_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.Workspaces')),
            ],
        ),
    ]
