# Generated by Django 3.0.6 on 2020-06-12 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_bookings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookings',
        ),
    ]
