# Generated by Django 3.0.6 on 2020-06-12 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0005_bookings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='User',
            new_name='user_booked',
        ),
    ]
